### ISSUE TITLE
Document upload & image preview

### ISSUE THREAD

**Issue by ahawkins** [yorzegroup/mono#10]
Users and business should be able to upload a document and preview the image in the browser.

**TODO**

- [ ] Automate KMS key
- [ ] Bake encryption into SDK
- [ ] Add upload to application
- [ ] Add preview to the application
